# Generated by Django 6.1 on 2026-09-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='category',
            field=models.CharField(default='main', max_length=30),
            preserve_default=False,
        ),
    ]
