# Generated by Django 6.1 on 2026-09-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_meal_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='category',
            field=models.CharField(choices=[('mainDishes', 'Hauptgericht'), ('desserts', 'Nachspeise'), ('drinks', 'Getränk')], max_length=30),
        ),
    ]
